baseURL = "https://loveu.ch"
languageCode = 'en-us'
theme = "coming-soon"

[params]
    title = "Für Kaya <3"
    favicon = ""
    message = "COMING SOON" 
    release = "june 9, 2024" 
    background = "" 
